export const AGENT_HOST = 'localhost:3001'

export const PROCESS_MONITOR_DATA_EMITTED = 'PROCESS_MONITOR_DATA_COLLECTED'
export const PROCESS_MONITOR_DATA_REQUESTED = 'PROCESS_MONITOR_DATA_REQUESTED'

export const FILE_EXPLORER_ROOT = '/home/bmq928'
export const FILE_EXPLORER_FILE_CONTENT_READ_REQUESTED = 'FILE_EXPLORER_FILE_CONTENT_READ_REQUESTED'
export const FILE_EXPLORER_FILE_CONTENT_READ_DONE = 'FILE_EXPLORER_FILE_CONTENT_READ_DONE'
export const FILE_EXPLORER_LIST_FOLDER_ITEM_REQUESTED = 'FILE_EXPLORER_LIST_FOLDER_ITEM_REQUESTED'
export const FILE_EXPLORER_LIST_FOLDER_ITEM_DONE = 'FILE_EXPLORER_LIST_FOLDER_ITEM_DONE'
export const FILE_EXPLORER_SHOW_FOLDER_TREE_REQUESTED = 'FILE_EXPLORER_SHOW_FOLDER_TREE_REQUESTED'
export const FILE_EXPLORER_SHOW_FOLDER_TREE_DONE = 'FILE_EXPLORER_SHOW_FOLDER_TREE_DONE'